coverage:
  status:
    patch: off
    project:
      default:
        target: 80%    # the required coverage value
        threshold: 10%  # the leniency in hitting the target

ignore:
  - src/mach3sbitools/examples/
