class SBITrainingException(Exception):
    ...

class OptimizerNotSpecified(SBITrainingException):
    ...

class ScalarNotSpecified(SBITrainingException):
    ...

class DensityEstimatorError(SBITrainingException):
    ...