---
name: pyMaCh3-integration
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mach3-software/mach3:alma9v1.3.0

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Virtualenv
        run: |
          uv python install 3.11
          uv venv --python 3.11 .venv

      - name: Install dependencies
        run: uv pip install --python .venv .

      - name: Clone MaCh3
        env:
          CMAKE_ARGS: "-DPYTHON_ENABLED=ON"
        run: |
          cd /opt/
          git clone https://github.com/mach3-software/MaCh3Tutorial.git MaCh3Tutorial
          cd MaCh3Tutorial
          uv pip install --python $GITHUB_WORKSPACE/.venv .

      - name: Test with pytest
        env:
          MACH3: /opt/MaCh3Tutorial
          WORKSPACE: /__w/MaCh3SbiTools/MaCh3SbiTools
        run: |
          cd /opt/MaCh3Tutorial
          $WORKSPACE/.venv/bin/pytest $WORKSPACE/tests \
            --override-ini="addopts=" \
            --junitxml=junit/test-results.xml \
            --cov=mach3sbitools --cov-report=xml --cov-report=term-missing
